### ISSUE TITLE
Can't run - java.lang.InternalError

### ISSUE THREAD

**Issue by flawmop** [flawmop/run-input-processing-svc#1]
Thought updating to Java 21 fixed this but apparently not.

```
java.lang.InternalError: java.lang.reflect.InvocationTargetException
    at com.oracle.svm.core.containers.Metrics.systemMetrics(Metrics.java:67)
    at com.oracle.svm.core.containers.Container.metrics(Container.java:44)
    at com.oracle.svm.core.ContainerInfo.<init>(ContainerInfo.java:34)
    at com.oracle.svm.core.Containers.memoryLimitInBytes(Containers.java:126)
    at com.oracle.svm.core.heap.PhysicalMemory.size(PhysicalMemory.java:92)
    at com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:362)
    at com.oracle.svm.core.JavaMainWrapper$EnterCreateIsolateWithCArgumentsPrologue.enter(JavaMainWrapper.java:414)
```

**Comment by flawmop** [comment]
Was using a legacy image!
